import express from 'express';
import http from 'http';

// @ts-ignore -- This will be generated by SvelteKit later
import { handler } from '../client/handler.js';
// add .js extension so it can be located after compiling typescript
import { setUpLiveReloadForDevelopment } from './devUtility.js';
import process from './processType.js';
import getSocketServer from './socketManagement.js';

const port = (process.env.PORT === undefined) ? 3000 : process.env.PORT;
const app = express();
const server = new http.Server(app);
server.listen(port);

setUpLiveReloadForDevelopment(app);
const socketServer = getSocketServer(server);
app.use(handler);


