name: Setup Project
on:
  push:
    branches: [SvelteApp, master] 
jobs:
  build:
    # We're running on ubuntu-latest, nothing special
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base repository
        uses: actions/checkout@v3
      - name: Get node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - name: Setup project
        run: npm run setup
